### ISSUE TITLE
Update Flutter samples

### ISSUE THREAD

**Issue by TahaTesser** [codemagic-ci-cd/codemagic-sample-projects#104]
Looks like all the Flutter samples currently have `flutter build apk --release ` 

For instance
https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/d1e842b706861b7f067ae5477903e68363a9cb11/Firebase-App-Distribution/codemagic_firebase_app_distribution_yaml-master/codemagic.yaml#L50

Google requires an app bundle for publishing new apps from Aug 2021.

https://android-developers.googleblog.com/2021/06/the-future-of-android-app-bundles-is.html

Also, Flutter docs prefer app bundles too.
https://docs.flutter.dev/deployment/android#building-the-app-for-release

### Solution

Update all Flutter samples including [this](https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/Firebase-App-Distribution/codemagic_firebase_app_distribution_yaml-master)

**Comment by TahaTesser** [comment]
Also "Install Pods" is included in the "Android Workflow". 
iOS commands should be removed from Android workflows.

https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/d1e842b706861b7f067ae5477903e68363a9cb11/Firebase-App-Distribution/codemagic_firebase_app_distribution_yaml-master/codemagic.yaml#L45-L47

**Comment by TahaTesser** [comment]
Just leaving this feedback for anyone updating Flutter samples

- Update `codemagic.yaml` files to update to match CM docs closely. 
- Update SDK constraints and migrate code samples to null-safety.
- Remove trailing spaces `.yaml` files.

**Comment by K-Codemagic** [comment]
Projects are updated.
