### ISSUE TITLE
No artifacts were found in Unity Build

### ISSUE THREAD

**Issue by mudassarjinnbyte** [codemagic-ci-cd/codemagic-sample-projects#107]
Hi, We are facing issue in artifacts section in codemagic.yaml file. Everything is just fine but wen creating build it says 

**== Gathering artifacts ==
No artifacts were found**

articats are mentioned in yaml file. We followed these guidelines to create Unity application
[Building Unity mobile apps
](https://docs.codemagic.io/yaml-quick-start/building-a-unity-app/)
Please help what could be the issue.

**Comment by icarusdust** [comment]
Hi @mudassarjinnbyte possibly, your artefacts paths are not correct or you are not executing build scripts or anything really. Please provide a build link, so that I can look into it.

**Comment by mudassarjinnbyte** [comment]
Hi, I have solved the issue by accessing remote machine. Actual issue was in keystore path in environment variable. Path was starting with "/" . So the error was on creating build . but codemagic was not showing any error but saying "No artifacts were found"
