### ISSUE TITLE
This needs a README file

### ISSUE THREAD

**Issue by enigmathix** [codemagic-ci-cd/codemagic-sample-projects#127]
Here at least: https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/ios/ios-automatic-code-signing-demo-project

**Comment by todah-zg** [comment]
As suggested in the other thread, please follow the [guide in the documentation site](https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/) for iOS code signing.

There is also a guide on [Alternative code signing methods](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/) that covers "Automatic iOS code signing" applied in the sample project that you link, but the new code signing method is much simpler and less error-prone that I warmly recommend it.

The readme file for the sample project that you mention is coming soon as well.
