### ISSUE TITLE
script `Build .ipa` exited with status code 65

### ISSUE THREAD

**Issue by Blulabs-Santoshi** [codemagic-ci-cd/codemagic-sample-projects#128]
I am stuck here

<img width="782" alt="image" src="https://user-images.githubusercontent.com/110805479/200586285-3db067e1-624e-421c-a5e1-61fe1d84c28d.png">
here is a script in my yaml file

`- name: Build .ipa
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"`

**Comment by todah-zg** [comment]
This repository holds sample projects showcasing how to use Codemagic to build and publish your mobile apps. You can raise a new Issue if you find an error with the sample projects repository.

To ask general questions about Codemagic and get support in using the service, please go to our [GitHub Discussions](https://github.com/codemagic-ci-cd/codemagic-docs/discussions) section of our Documentation repository.
