### ISSUE TITLE
Flutter yaml samples without `instance_type` throws an error

### ISSUE THREAD

**Issue by TahaTesser** [codemagic-ci-cd/codemagic-sample-projects#153]
When copying `codemagic.yaml` from [ Flutter YAML sample ](https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/flutter/flutter-android-and-ios-yaml-demo-project)  and run it in my project it throws following error:

![Screenshot 2023-03-31 at 01 31 38](https://user-images.githubusercontent.com/48603081/228978274-47a65e6a-8038-4bef-905c-bec72b311e84.png)

I had to fix this by specifying instance type `instance_type: mac_mini_m1` and run the build again.

**Comment by nevercode-kevin** [comment]
@himesh-cm - please add mac_mini_m1 instance type to Android and iOS workflows [here](https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/flutter/flutter-android-and-ios-yaml-demo-project/codemagic.yaml)

**Comment by himesh-cm** [comment]
Closing this issue - [PR](https://github.com/codemagic-ci-cd/codemagic-sample-projects/pull/154) was merged.
