### ISSUE TITLE
Unable to build apk in codmagic No suitable keystores found matching reference "codemagic.keystore"

### ISSUE THREAD

**Issue by ramuramasani** [codemagic-ci-cd/codemagic-sample-projects#200]
**Describe the sample projects update you'd like to see**
We are getting the mentioned error while configuring the keystore with code magic.

No suitable keystores found matching reference "codemagic.keystore". Available options are: Crop Watch

FYI, Crop Watch is our project name

**Additional context**
NA

**Getting support**
NA

**Comment by icarusdust** [comment]
Hi @ramuramasani, as I understand you are facing issues when building your Android app. If so, please open a thread in the Discussions channel: https://github.com/orgs/codemagic-ci-cd/discussions. 
I am closing the issue thread here.
