### ISSUE TITLE
 exited with status code 1

### ISSUE THREAD

**Issue by maulikTeksun** [codemagic-ci-cd/codemagic-sample-projects#35]
Hello there I am integrating the Codemagic in my  iOS App.

I am getting  **exited with status code 1** error at scripts when doing pod install.

like,

scripts:
        - name: Install pods
          script: |
            pod install

**Comment by icarusdust** [comment]
Hi, sorry for the late reply. If you are still having the issue. Sadly, it is hard to debug the issue with the above-mentioned description, please either post the question in our community slack channel or you can directly send it to nihal@nevercode.io
