### ISSUE TITLE
Readme files seem to contain old info about securing environment variables

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/codemagic-sample-projects#75]
Some readme files have the following:

> Encrypted Environment Variables
> Use the Codemagic web app to securely encrypt environment variables that are included in the codemagic.yaml. These values can only be accessed on the Codemagic build servers.
> 
> Please note that encrypted values are specific to your personal account or team. If you move your app from personal account to a Team or vice versa you will need to re-encrypt these values.

Let's revise current repos and update with new approach where variables are defined in Codemagic application in team level, app level and workflow level. 

Encryption API remains active, but seems better to keep it simple in these cases.

**Comment by icarusdust** [comment]
Will update them.

**Comment by icarusdust** [comment]
PR merged, closing here.
