### ISSUE TITLE
Add Example for Testlab and IOS

### ISSUE THREAD

**Issue by eduardo-fischer-avenue** [codemagic-ci-cd/codemagic-sample-projects#76]
I'm currently trying to add testlab to my flutter integration tests. 
There are examples about how to do it with Android but none about IOS.

**Comment by nevercode-kevin** [comment]
Documented here:
https://docs.codemagic.io/yaml-testing/firebase-test-lab/#ios

If the documentation doesn't explain clearly enough, please open an issue in the docs repository https://github.com/codemagic-ci-cd/codemagic-docs
